version: '3'

services:
  rmq:
    build: rmq
    hostname: rmq_host
    environment:
      - LOG=debug
  perf-test:
    image: pivotalrabbitmq/perf-test:latest
    command:
      - --uri=amqp://rmq_host
      - --servers-startup-timeout=45
      - --rate=10
      - --producers=2
      - --consumers=2
      - --confirm=32
      - --confirm-timeout=800
      - --flag=mandatory
      - --flag=persistent
      - --queue-args=x-queue-type=quorum
      - --auto-delete=false
      - --queue-pattern='perf-test-%03d'
      - --queue-pattern-from=0
      - --queue-pattern-to=9
    depends_on:
      - rmq
    restart: on-failure
