version: '3'

services:
  rmq:
    build: rmq
    environment:
      - LOG=debug
  perf-test:
    image: pivotalrabbitmq/perf-test:latest
    command:
      - --uri=amqp://guest:guest@rmq:5672
      - --servers-startup-timeout=10
      - --rate=10
      - --producers=1
      - --consumers=1
      - --confirm=4
      - --confirm-timeout=800
      - --flag=mandatory
      - --flag=persistent
      - --queue-args=x-queue-type=quorum
      - --auto-delete=false
      - --queue-pattern='perf-test-%03d'
      - --queue-pattern-from=0
      - --queue-pattern-to=9
    depends_on:
      - rmq
    restart: on-failure
